---
title: "Bulkley River Watershed Group - Fish Passage Planning - Progress Report"
author: "New Graph Environment"
date: 
output: html_document
---

```{r setup, include = TRUE, echo =FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE,
                      fig.align="center", fig.width = 5.118, fig.height = 3.409,
                      fig.path = ('fig/'))
# knitr::opts_chunk$set(echo = TRUE)
source('R/packages.R')
source("R/functions.R")
```

Preliminary results are also summarized in kml format here at https://github.com/NewGraphEnvironment/Bulkley_Planning/raw/master/data/outgoing/bulkley_progress_kml.zip
```{r import-pscis, eval=F}
##these are necessary for the leaflet map
##import the phase 1 data for CWF and turn into spatial file
pscis_phase1_sf <- import_pscis(workbook_name = 'pscis_phase1.xlsm') %>% 
  sf::st_as_sf(coords = c("easting", "northing"), 
               crs = 26909, remove = F)
  
  
##import phase 2 data and turn into spatial file
pscis_phase2_sf <-  import_pscis(workbook_name = 'pscis_phase2.xlsm') %>%  
  sf::st_as_sf(coords = c("easting", "northing"), 
               crs = 26909, remove = F)

##import phase 2 data and turn into spatial file
pscis_reassessments_sf <-  import_pscis(workbook_name = 'pscis_reassessments.xlsm') %>%  
  sf::st_as_sf(coords = c("easting", "northing"), 
               crs = 26909, remove = F)
```

```{r burn-kmls}
##get the names of your pscis files
workbooks <-  list.files(path = 'data', pattern = "pscis", all.files = F) %>% 
  grep(pattern = '~', invert = T, value = T)

##make a function to import and add the source
make_pscis_kml <- function(workbook){
  import_pscis(workbook_name = workbook)  %>% 
    make_kml_col()  %>%  
    # dplyr::group_split(site_id) %>% ##going to do this later
    # purrr::map(make_html_tbl) %>% ##going to do this later
    dplyr::bind_rows() %>% 
    dplyr::mutate(source = tools::file_path_sans_ext(workbook))
}

##import and combine all your pscis assessments
df <- workbooks %>% 
  map_df(make_pscis_kml) %>% 
  dplyr::mutate(sort = case_when(source %like% 'phase1' ~ 2,
                                 source %like% 'phase2' ~ 1,
                                 T ~ 3),
                shape = case_when(source %like% 'phase1' ~ "http://maps.google.com/mapfiles/kml/paddle/A.png",
                                  source %like% 'phase2' ~ "http://maps.google.com/mapfiles/kml/paddle/C.png",
                                  T ~ "http://maps.google.com/mapfiles/kml/paddle/R.png")) %>%
  dplyr::arrange(sort) %>% 
  dplyr::distinct(site_id, .keep_all = T)
  # dplyr::select(road_name:barrier_result, photo_link, assessment_comment)

#if we want the mapsheet we need to get it before making the html table. no time right now.
##get the mapsheet id for each of the crossings
##get the mapsheet id
conn <- dbConnect(
  RPostgres::Postgres(),
  dbname = 'postgis',
  host = 'localhost',
  port = 5432,
  user = 'postgres',
  password = 'postgres'
)

##list column names in a table
# dbGetQuery(conn,
#            "SELECT column_name,data_type
#            FROM information_schema.columns
#            WHERE table_name='dbm_mof_50k_grid'")

##make into spatial object
df_sf <- df %>%
  sf::st_as_sf(coords = c("easting", "northing"),
               crs = 26909, remove = F) %>%
  st_transform(crs = 3005) 


# load to database
st_write(obj = df_sf, dsn = conn, Id(schema= "working", table = "misc_points"))

# sf doesn't automagically create a spatial index or a primary key
res <- dbSendQuery(conn, "CREATE INDEX ON working.misc_points USING GIST (geometry)")
dbClearResult(res)
res <- dbSendQuery(conn, "ALTER TABLE working.misc_points ADD PRIMARY KEY (site_id)")
dbClearResult(res)



mapsheet_id <- dbGetQuery(conn,
                                  "
                                  SELECT x.site_id, y.map_tile_display_name
                                  FROM working.misc_points x
                                  INNER JOIN
                                  whse_basemapping.dbm_mof_50k_grid y
                                  ON ST_Intersects(x.geometry,y.geom)")
dbDisconnect(conn = conn)

##add the mapsheet back to the df
df <- left_join(
  df,
  mapsheet_id,
  by = "site_id"
)


df <- df %>% 
  dplyr::group_split(site_id) %>% 
  purrr::map(make_html_tbl) %>% 
  dplyr::bind_rows()

coords <- df %>% select(easting, northing)
proj4string <- sp::CRS("+init=epsg:32609")
df <- df %>% 
  sp::SpatialPointsDataFrame(coords = coords, proj4string = proj4string) %>% 
  plotKML::reproject()

##create the outgoing directory if it is not already there
targetdir = paste0(getwd(), "/data")
targetdir = paste0(getwd(), "/data/outgoing")
dir.create(targetdir)


##we need to clear out the old kmls
##now we will zip up the kml files in the data folder and rename with kmz
files_to_clear <- paste0("data/outgoing/", list.files(path = "data/outgoing/", pattern = "\\.kml$")) 
file.remove(files_to_clear)


##burn to kml
##specify shape
# shape = "http://maps.google.com/mapfiles/kml/pal2/icon18.png"
shape = "http://maps.google.com/mapfiles/kml/paddle/A.png"
# shape = "http://maps.google.com/mapfiles/kml/pal5/icon56.png"


##get teh name of the folder we are in
# bname <- basename(dirname(dirname(getwd())))

##or alternatively - give the file an identifier
bname <- "2020_bulkley"


# kml_open("data/outgoing/barrier_assessments.kml")
kml_open(paste0("data/outgoing/",bname, "_PASSAGE_assessments.kml"))
kml_layer(df, shape = df$shape, colour = df$color, labels = df$label, html.table = df$html_tbl, z.scale = 2, LabelScale = 1, size = 2)
kml_close(paste0("data/outgoing/",bname, "_PASSAGE_assessments", format(Sys.time(),"_%Y%m%d_%H%M.kml")))

```

```{r summarise-habitat}
##now get the phase 2 sites only to add the habitat info
##bring in the data, make a html table of each row↑
df <- import_pscis(workbook_name = 'pscis_phase2.xlsm') %>% 
  make_kml_col() 


habitat_data <- import_fish_data() %>% 
  pluck('step_4_stream_site_data')

habitat_data_summary <- habitat_data %>% 
  select(gazetted_names, local_name, avg_channel_width_m, 
         avg_wetted_width_m,
         average_gradient_percent, comments) %>% 
  mutate(average_gradient_percent = average_gradient_percent * 100) %>% 
  mutate(across(where(is.numeric), round, 1)) %>% 
  tidyr::separate(local_name, into = c('site_id', 'location'), remove = F) %>% 
  dplyr::mutate(site_id = as.numeric(site_id)) %>% 
  dplyr::select(-local_name)

##add the info from the priorities
priorities_spreadsheet <-  readxl::read_excel(path = "./data/priorities.xlsx") %>% 
  tidyr::separate(local_name, into = c('site_id', 'location'), remove = F) %>% 
  readr::type_convert()

habitat_data_summary <- left_join(
  habitat_data_summary,
  select(priorities_spreadsheet, site_id, location, survey_length_m, electrofishing, minnowtrapping, uav_survey),
  by = c('site_id', 'location')
)  %>% 
  dplyr::mutate(photo_link = paste0(
    'https://github.com/NewGraphEnvironment/Bulkley_Planning/tree/master/data/photos/', site_id, '/crossing_all.JPG')) %>% 
  mutate(photo_link = cell_spec('crossing', "html", link = photo_link)) %>% 
  select(gazetted_names:average_gradient_percent, survey_length_m:uav_survey, photo_link, everything())






##lets make tables for each site that has habitat data for that site
##bring in the data, make a html table of each row
hab_html_tbl <- habitat_data_summary %>% 
  dplyr::group_split(site_id) %>% 
  purrr::map(make_html_tbl_hab) %>%
  dplyr::bind_rows() %>% 
  select(site_id, html_tbl) %>% 
  dplyr::distinct() %>% 
  mutate(site_id = as.integer(site_id))


##lets see that we have everything
# result <- as_tibble(hab_html_tbl$site_id %in% df$site_id)
# chk <- bind_cols(as_tibble(test), result)

##join some pscis info with our hab table and make another kml
df_hab <- left_join(
  select(df, site_id, label, easting, northing),
  hab_html_tbl,
  by = 'site_id'
) 



```

```{r}
coords <- df_hab %>% select(easting, northing)
proj4string <- sp::CRS("+init=epsg:32609")
df_kml <- df_hab %>% 
  sp::SpatialPointsDataFrame(coords = coords, proj4string = proj4string) %>% 
  plotKML::reproject()
 
##burn to kml
##specify shape
shape = "http://maps.google.com/mapfiles/kml/shapes/fishing.png"
# shape2 = "http://maps.google.com/mapfiles/kml/pal5/icon50.png"


# filename <- paste0(name,format(Sys.time(),"_%Y%m%d_%H%M.kml"))
kml_open(paste0("data/outgoing/",bname, "_HABITAT_assessments", format(Sys.time(),"_%Y%m%d_%H%M.kml")))
kml_layer(df_kml, shape = shape, colour = 'yellow', labels = label, html.table = df_kml$html_tbl, z.scale = 2, LabelScale = 1, size = 2)
kml_close(paste0("data/outgoing/",bname, "_HABITAT_assessments", format(Sys.time(),"_%Y%m%d_%H%M.kml")))
```

```{r zip-kml}
##now we will zip up the kml files in the data folder and rename with kmz
files_to_zip <- paste0("data/outgoing/", list.files(path = "data/outgoing/", pattern = "\\.kml$"))  ##this used to includes the planning file which we don't want to do so watch out
zip::zipr("data/outgoing/bulkley_progress_kml.zip", files = files_to_zip)  ##it does not work to zip to kmz!!


```


```{r leaflet-map, eval=T}
##transfor to wsg84
df_sf <- df_sf %>% 
  st_transform(crs = 4326)

##make colors for the priorities
pal <- 
   colorFactor(palette = c("red", "yellow", "green"), 
               levels = c("Barrier", "Potential", "Passable"))


map <- leaflet(height=500, width=780) %>%
  # leaflet() %>% 
  addTiles() %>%
  leafem::addMouseCoordinates(proj4 = 26911) %>% ##can't seem to get it to render utms yet
  addProviderTiles(providers$"Esri.DeLorme") %>% 
  # addProviderTiles("Esri.WorldTopoMap", group = "Topo") %>%
  addProviderTiles("Esri.WorldImagery", group = "ESRI Aerial") %>% 
  # addPolylines(data=drake::readd(fish_habitat_model_lines),  opacity=1, color = '#6498d2',
  #              fillOpacity = 0.75, weight=2) %>% 
  # addPolylines(data=forest_tenure_road_lines,  opacity=1, color = '#ff7f00',
  #              fillOpacity = 0.75, weight=2) %>%
  # addPolylines(data=tracks,  opacity=0.75, color = '#e216c4',
  #              fillOpacity = 0.75, weight=5) %>%
  addLegend(
    position = "topright",
    colors = c("red", "yellow", "green"),
    labels = c("Barrier", "Potential Barrier", "Passable"), opacity = 1,
    title = "Bulkley River Fish Passage Restoration Planning",
  ) %>%
  # addAwesomeMarkers(lng = photo_metadata$lon_map,lat = photo_metadata$lat_map,
  #                   popup = leafpop::popupImage(photo_metadata$url, src = "remote"),
  #                   clusterOptions = markerClusterOptions(),
  #                   labelOptions = offset(c(0,0)),
  #                   label = paste0(photo_metadata$crossing_id, '_', photo_metadata$filename)) %>%
    addCircleMarkers(
    data=df_sf,
    label = df_sf$site_id,
    popup = leafpop::popupTable(x = select((df_sf %>% st_set_geometry(NULL)), 
                                           Site = site_id, Stream = stream_name, Road = road_name, 
                                           Comments = assessment_comment),
                                feature.id = F,
                                row.numbers = F), 
    radius = 9,
    fillColor = ~pal(barrier_result),
    color= "#ffffff",
    stroke = TRUE, 
    fillOpacity = 1.0,
    weight = 2,
    opacity = 1.0
  ) %>% 
  addScaleBar(position = 'bottomleft', options = scaleBarOptions(imperial = FALSE)) %>% 
  addLayersControl(
    baseGroups = c(
      "Esri.DeLorme",
      "ESRI Aerial"),
    # overlayGroups = c(my_tracks$`125000_ds_track`),
    options = layersControlOptions(collapsed = F)) %>% 
  
  addMiniMap(tiles = providers$"Esri.NatGeoWorldMap",
             zoomLevelOffset = -6)    # setView(lng = -105.644, lat = 51.618, zoom = 3) ##this becomes the latest and greatest pscis crossing utm
map

```

```{r include= FALSE, echo=FALSE, comment=NA, message=FALSE, warning=FALSE, eval=F}

rmarkdown::render(input = paste0('report-progress.Rmd'),  
                    output_file = 'docs/index.html') 
```
